version: "3.9"
version: "3.0"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    image: zki/web
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
    command: >
      bash -c "python manage.py makemigrations installment &&
      python manage.py makemigrations purchase &&
      python manage.py makemigrations settings &&
      python manage.py makemigrations system &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks: 
      - app_network
    depends_on:
      - db
networks: 
  app_network: