version: "3.9"
version: "3.0"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks: 
      - network
  web:
    image: zki:${IMAGE_VERSION}
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
    command: >
      bash -c "python manage.py makemigrations installment &&
      python manage.py makemigrations purchase &&
      python manage.py makemigrations settings &&
      python manage.py makemigrations system &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "${HOST_PORT}:${SERVER_PORT}"
    networks: 
      - network
    depends_on:
      - db
networks: 
  network:
  